version: "3.9"

services:
  app:
    build: .
    container_name: bidhouse-app
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: bidhouse-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: bidhouse
      MYSQL_USER: bidhouse_user
      MYSQL_PASSWORD: bidhouse_pass
    ports:
      - "3307:3306" # optional, kalau mau akses dari host
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
